# Generated by Django 3.1.8 on 2021-04-28 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transients_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='asteroid',
            name='absolute_magnitude',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='asteroid',
            name='apparent_magnitude',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='asteroid',
            name='dec',
            field=models.FloatField(null=True, verbose_name='dec'),
        ),
        migrations.AddField(
            model_name='asteroid',
            name='ra',
            field=models.FloatField(null=True, verbose_name='ra'),
        ),
        migrations.AddField(
            model_name='asteroid',
            name='timestamp',
            field=models.DateTimeField(null=True),
        ),
    ]
