# Generated by Django 3.1.8 on 2021-05-02 17:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('transients_app', '0002_auto_20210428_1650'),
    ]

    operations = [
        migrations.RenameField(
            model_name='asteroid',
            old_name='apparent_magnitude',
            new_name='visual_magnitude',
        ),
    ]
