# Generated by Django 3.1.9 on 2021-07-03 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Exoplanet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pl_name', models.CharField(max_length=30, verbose_name='Planet Name')),
                ('hostname', models.CharField(max_length=30, verbose_name='Host Name')),
                ('sy_snum', models.IntegerField(verbose_name='Number of Stars')),
                ('sy_pnum', models.IntegerField(verbose_name='Number of Planets')),
                ('disc_year', models.IntegerField(verbose_name='Discovery Year')),
                ('soltype', models.CharField(max_length=30, verbose_name='Solution Type')),
                ('pl_rade', models.FloatField(verbose_name='Planet Radius [Earth Radius]')),
                ('pl_bmasse', models.FloatField(verbose_name='Planet Mass or Mass*sin(i) [Earth Mass]')),
                ('st_spectype', models.CharField(max_length=30, verbose_name='Spectral Type')),
                ('ra', models.FloatField(null=True)),
                ('dec', models.FloatField(null=True)),
                ('sy_dist', models.FloatField(null=True)),
                ('sy_vmag', models.FloatField(null=True)),
            ],
        ),
    ]
