# Generated by Django 3.1.9 on 2021-07-03 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exoplanets', '0003_auto_20210703_1542'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exoplanet',
            name='gaia_name',
            field=models.CharField(max_length=15, null=True, verbose_name='GAIA ID'),
        ),
        migrations.AlterField(
            model_name='exoplanet',
            name='hd_name',
            field=models.CharField(max_length=15, null=True, verbose_name='HD ID'),
        ),
        migrations.AlterField(
            model_name='exoplanet',
            name='hip_name',
            field=models.CharField(max_length=15, null=True, verbose_name='HIP ID'),
        ),
        migrations.AlterField(
            model_name='exoplanet',
            name='hostname',
            field=models.CharField(max_length=15, null=True, verbose_name='Host Name'),
        ),
        migrations.AlterField(
            model_name='exoplanet',
            name='pl_bmasse',
            field=models.CharField(max_length=30, null=True, verbose_name='Planet Mass or Mass*sin(i) [Earth Mass]'),
        ),
        migrations.AlterField(
            model_name='exoplanet',
            name='pl_letter',
            field=models.CharField(max_length=2, null=True, verbose_name='Planet Letter'),
        ),
        migrations.AlterField(
            model_name='exoplanet',
            name='pl_name',
            field=models.CharField(max_length=15, verbose_name='Planet Name'),
        ),
        migrations.AlterField(
            model_name='exoplanet',
            name='pl_rade',
            field=models.CharField(max_length=30, null=True, verbose_name='Planet Radius [Earth Radius]'),
        ),
        migrations.AlterField(
            model_name='exoplanet',
            name='st_spectype',
            field=models.CharField(max_length=10, null=True, verbose_name='Spectral Type'),
        ),
        migrations.AlterField(
            model_name='exoplanet',
            name='tic_name',
            field=models.CharField(max_length=15, null=True, verbose_name='TESS ID'),
        ),
    ]
