# Generated by Django 3.1.9 on 2021-07-03 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exoplanets', '0004_auto_20210703_1608'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exoplanet',
            name='gaia_name',
            field=models.CharField(max_length=30, null=True, verbose_name='GAIA ID'),
        ),
        migrations.AlterField(
            model_name='exoplanet',
            name='sy_dist',
            field=models.CharField(max_length=15, null=True),
        ),
    ]
