# Generated by Django 3.1.9 on 2021-07-03 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exoplanets', '0005_auto_20210703_1612'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exoplanet',
            name='pl_name',
            field=models.CharField(max_length=30, verbose_name='Planet Name'),
        ),
        migrations.AlterField(
            model_name='exoplanet',
            name='sy_vmag',
            field=models.CharField(max_length=15, null=True),
        ),
    ]
