# Generated by Django 3.1.9 on 2021-07-03 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exoplanets', '0006_auto_20210703_1615'),
    ]

    operations = [
        migrations.AddField(
            model_name='exoplanet',
            name='disc_facility',
            field=models.CharField(max_length=30, null=True, verbose_name='Discovery Facility'),
        ),
    ]
