# Generated by Django 3.1.9 on 2021-07-03 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exoplanets', '0007_exoplanet_disc_facility'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exoplanet',
            name='pl_name',
            field=models.CharField(max_length=30, unique=True, verbose_name='Planet Name'),
        ),
    ]
