# Generated by Django 3.1.13 on 2022-05-01 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('starcharts_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='starchart',
            name='file',
        ),
        migrations.AlterField(
            model_name='starchart',
            name='image',
            field=models.ImageField(upload_to='my_starmaps'),
        ),
    ]
