# Generated by Django 3.1.13 on 2022-05-01 14:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('starcharts_app', '0002_auto_20220501_1212'),
    ]

    operations = [
        migrations.RenameField(
            model_name='starchart',
            old_name='title',
            new_name='name',
        ),
    ]
