# Generated by Django 3.1.13 on 2022-05-08 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('starcharts_app', '0003_auto_20220501_1636'),
    ]

    operations = [
        migrations.AddField(
            model_name='starchart',
            name='diagram_size',
            field=models.IntegerField(default=800),
        ),
        migrations.AddField(
            model_name='starchart',
            name='display_height',
            field=models.IntegerField(default=700),
        ),
        migrations.AddField(
            model_name='starchart',
            name='display_width',
            field=models.IntegerField(default=1200),
        ),
        migrations.AddField(
            model_name='starchart',
            name='font_color',
            field=models.CharField(default='#167ac6', max_length=10),
        ),
        migrations.AddField(
            model_name='starchart',
            name='font_size',
            field=models.IntegerField(default=8),
        ),
        migrations.AlterField(
            model_name='starchart',
            name='name',
            field=models.CharField(default='change me', max_length=15),
        ),
    ]
