# Generated by Django 3.1.13 on 2022-05-08 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('starcharts_app', '0004_auto_20220508_1850'),
    ]

    operations = [
        migrations.AddField(
            model_name='starchart',
            name='brightest_mag',
            field=models.FloatField(default=-1.5),
        ),
        migrations.AddField(
            model_name='starchart',
            name='dimmest_mag',
            field=models.FloatField(default=8),
        ),
    ]
