# Generated by Django 3.1.13 on 2022-05-11 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('starcharts_app', '0005_auto_20220508_1908'),
    ]

    operations = [
        migrations.AddField(
            model_name='starchart',
            name='coords_color',
            field=models.CharField(default='#FFF', max_length=10),
        ),
        migrations.AddField(
            model_name='starchart',
            name='coords_size',
            field=models.IntegerField(default=12),
        ),
        migrations.AddField(
            model_name='starchart',
            name='curve_color',
            field=models.CharField(default='#FFF', max_length=10),
        ),
        migrations.AddField(
            model_name='starchart',
            name='curve_width',
            field=models.FloatField(default=0.1),
        ),
        migrations.AddField(
            model_name='starchart',
            name='max_diameter',
            field=models.IntegerField(default=4),
        ),
        migrations.AddField(
            model_name='starchart',
            name='min_diameter',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='starchart',
            name='star_color',
            field=models.CharField(default='#FFF', max_length=10),
        ),
    ]
