# Generated by Django 3.1.13 on 2022-05-11 14:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('starcharts_app', '0006_auto_20220511_1629'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='starchart',
            name='coords_color',
        ),
        migrations.RemoveField(
            model_name='starchart',
            name='coords_size',
        ),
    ]
