# Generated by Django 3.1.13 on 2022-05-14 13:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('starcharts_app', '0009_auto_20220514_1325'),
    ]

    operations = [
        migrations.RenameField(
            model_name='starchart',
            old_name='background_color',
            new_name='background',
        ),
    ]
