# Generated by Django 3.1.13 on 2022-05-14 13:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('starcharts_app', '0010_auto_20220514_1524'),
    ]

    operations = [
        migrations.RenameField(
            model_name='starchart',
            old_name='max_diameter',
            new_name='max_d',
        ),
        migrations.RenameField(
            model_name='starchart',
            old_name='min_diameter',
            new_name='min_d',
        ),
    ]
