# Generated by Django 3.1.13 on 2022-05-15 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('starcharts_app', '0011_auto_20220514_1528'),
    ]

    operations = [
        migrations.CreateModel(
            name='Scheme',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='default', max_length=15)),
                ('magnitude_limit', models.FloatField(default=10)),
                ('dimmest_mag', models.FloatField(default=8)),
                ('brightest_mag', models.FloatField(default=-1.5)),
                ('min_d', models.IntegerField(default=1)),
                ('max_d', models.IntegerField(default=4)),
                ('font_size', models.IntegerField(default=10)),
                ('font_color', models.CharField(default='#167ac6', max_length=10)),
                ('curve_width', models.FloatField(default=0.2)),
                ('curve_color', models.CharField(default='#FFF', max_length=10)),
                ('star_color', models.CharField(default='#FFF', max_length=10)),
                ('background', models.CharField(default='black', max_length=10)),
            ],
        ),
    ]
