# Generated by Django 3.1.13 on 2022-05-15 09:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('starcharts_app', '0013_remove_starchart_scheme'),
    ]

    operations = [
        migrations.AddField(
            model_name='starchart',
            name='scheme',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='starcharts_app.scheme'),
        ),
    ]
