# Generated by Django 3.1.13 on 2022-05-15 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('starcharts_app', '0014_starchart_scheme'),
    ]

    operations = [
        migrations.AlterField(
            model_name='starchart',
            name='name',
            field=models.CharField(default='change me', max_length=30),
        ),
    ]
