# Generated by Django 3.1.13 on 2022-05-15 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('starcharts_app', '0016_auto_20220515_1216'),
    ]

    operations = [
        migrations.AddField(
            model_name='starchart',
            name='previous_scheme_name',
            field=models.CharField(max_length=30, null=True),
        ),
    ]
