# Generated by Django 3.1.13 on 2022-05-15 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('starcharts_app', '0018_auto_20220515_1933'),
    ]

    operations = [
        migrations.AddField(
            model_name='stars',
            name='HenryDraperID',
            field=models.CharField(default=0, max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='stars',
            name='HipparcosID',
            field=models.CharField(default=0, max_length=10),
            preserve_default=False,
        ),
    ]
