# Generated by Django 3.1.13 on 2022-05-21 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('starcharts_app', '0020_auto_20220521_1455'),
    ]

    operations = [
        migrations.AddField(
            model_name='stars',
            name='GlieseID',
            field=models.CharField(default=None, max_length=10),
        ),
    ]
