# Generated by Django 3.1.13 on 2022-05-21 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('starcharts_app', '0021_stars_glieseid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stars',
            name='AbsoluteMagnitude',
            field=models.FloatField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name='stars',
            name='BayerFlamsteed',
            field=models.CharField(default=None, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='stars',
            name='ColorIndex',
            field=models.FloatField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name='stars',
            name='Constellation',
            field=models.CharField(default=None, max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='stars',
            name='DistanceInParsecs',
            field=models.FloatField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name='stars',
            name='GlieseID',
            field=models.CharField(default=None, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='stars',
            name='HenryDraperID',
            field=models.CharField(default=None, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='stars',
            name='HipparcosID',
            field=models.CharField(default=None, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='stars',
            name='Luminosity',
            field=models.FloatField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name='stars',
            name='Magnitude',
            field=models.FloatField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name='stars',
            name='ProperMotionDec',
            field=models.FloatField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name='stars',
            name='ProperMotionRA',
            field=models.FloatField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name='stars',
            name='RadialVelocity',
            field=models.FloatField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name='stars',
            name='SpectralType',
            field=models.CharField(default=None, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='stars',
            name='VariableMaximum',
            field=models.FloatField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name='stars',
            name='VariableMinimum',
            field=models.FloatField(default=None, null=True),
        ),
    ]
