# Generated by Django 3.1.13 on 2022-07-29 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('starcharts_app', '0023_auto_20220727_1456'),
    ]

    operations = [
        migrations.AddField(
            model_name='starchart',
            name='dec',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='starchart',
            name='ra',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='starchart',
            name='radius_dec',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='starchart',
            name='radius_ra',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='starchart',
            name='rotation',
            field=models.IntegerField(default=0),
        ),
    ]
