# Generated by Django 3.1.13 on 2022-07-29 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('starcharts_app', '0024_auto_20220729_1620'),
    ]

    operations = [
        migrations.AlterField(
            model_name='starchart',
            name='dec_max',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='starchart',
            name='dec_min',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='starchart',
            name='ra_max',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='starchart',
            name='ra_min',
            field=models.FloatField(null=True),
        ),
    ]
