# Generated by Django 3.1.13 on 2022-08-06 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('starcharts_app', '0025_auto_20220729_1648'),
    ]

    operations = [
        migrations.AddField(
            model_name='starchart',
            name='label_field',
            field=models.CharField(choices=[('HipparcosID', 'HipparcosID'), ('HenryDraperID', 'HenryDraperID'), ('GlieseID', 'GlieseID'), ('BayerFlamsteed', 'BayerFlamsteed'), ('ProperName', 'ProperName')], default='BayerFlamsteed', max_length=15),
        ),
        migrations.AddField(
            model_name='starchart',
            name='nr_of_stars',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='scheme',
            name='dimmest_mag',
            field=models.FloatField(default=6),
        ),
        migrations.AlterField(
            model_name='scheme',
            name='magnitude_limit',
            field=models.FloatField(default=7),
        ),
        migrations.AlterField(
            model_name='starchart',
            name='brightest_mag',
            field=models.FloatField(default=-2),
        ),
        migrations.AlterField(
            model_name='starchart',
            name='diagram_size',
            field=models.IntegerField(default=800),
        ),
        migrations.AlterField(
            model_name='starchart',
            name='dimmest_mag',
            field=models.FloatField(default=9),
        ),
        migrations.AlterField(
            model_name='starchart',
            name='display_height',
            field=models.IntegerField(default=600),
        ),
        migrations.AlterField(
            model_name='starchart',
            name='display_width',
            field=models.IntegerField(default=800),
        ),
        migrations.AlterField(
            model_name='starchart',
            name='max_d',
            field=models.IntegerField(default=6),
        ),
    ]
