# Generated by Django 3.1.13 on 2022-08-07 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('starcharts_app', '0027_auto_20220807_1240'),
    ]

    operations = [
        migrations.AlterField(
            model_name='starchart',
            name='previous_scheme_name',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
