# Generated by Django 3.1.13 on 2022-08-13 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('starcharts_app', '0028_auto_20220807_1326'),
    ]

    operations = [
        migrations.AddField(
            model_name='scheme',
            name='diagram_size',
            field=models.IntegerField(default=800),
        ),
        migrations.AddField(
            model_name='scheme',
            name='display_height',
            field=models.IntegerField(default=600),
        ),
        migrations.AddField(
            model_name='scheme',
            name='display_width',
            field=models.IntegerField(default=800),
        ),
        migrations.AddField(
            model_name='scheme',
            name='label_field',
            field=models.CharField(choices=[('HipparcosID', 'HipparcosID'), ('HenryDraperID', 'HenryDraperID'), ('GlieseID', 'GlieseID'), ('BayerFlamsteed', 'BayerFlamsteed'), ('ProperName', 'ProperName')], default='BayerFlamsteed', max_length=15),
        ),
        migrations.AddField(
            model_name='scheme',
            name='output_format',
            field=models.CharField(choices=[('svg', 'svg'), ('png', 'png')], default='svg', max_length=3),
        ),
        migrations.AddField(
            model_name='scheme',
            name='query_limit',
            field=models.IntegerField(default=10000),
        ),
        migrations.AddField(
            model_name='scheme',
            name='source',
            field=models.CharField(choices=[('ucac4_postgres', 'ucac4_postgres'), ('hyg_sqlite', 'hyg_sqlite')], default='ucac4_postgres', max_length=30),
        ),
    ]
