# Generated by Django 3.1.13 on 2022-08-13 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('starcharts_app', '0029_auto_20220813_1329'),
    ]

    operations = [
        migrations.AlterField(
            model_name='starchart',
            name='rotation',
            field=models.FloatField(default=0),
        ),
    ]
