# Generated by Django 2.2.6 on 2019-10-13 08:20

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TaskObject',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='unknown', max_length=100)),
                ('task_type', models.CharField(default='dataproduct', max_length=20)),
                ('taskID', models.CharField(blank=True, db_index=True, max_length=30, null=True, verbose_name='taskID')),
                ('creationTime', models.DateTimeField(blank=True, default=datetime.datetime.utcnow)),
                ('new_status', models.CharField(default='defined', max_length=50, null=True)),
                ('data_location', models.CharField(default='unknown', max_length=255, null=True)),
                ('my_status', models.CharField(db_index=True, default='defined', max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Observation',
            fields=[
                ('taskobject_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='backend_app.TaskObject')),
                ('date', models.DateTimeField(null=True, verbose_name='start time')),
                ('process_type', models.CharField(default='observation', max_length=50)),
                ('field_name', models.CharField(max_length=50, null=True)),
                ('field_ra', models.FloatField(null=True, verbose_name='field_ra')),
                ('field_dec', models.FloatField(null=True, verbose_name='field_dec')),
                ('field_fov', models.FloatField(null=True, verbose_name='field_fov')),
                ('quality', models.CharField(default='unknown', max_length=30)),
            ],
            bases=('backend_app.taskobject',),
        ),
        migrations.CreateModel(
            name='Status',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='unknown', max_length=50)),
                ('timestamp', models.DateTimeField(blank=True, default=datetime.datetime.utcnow)),
                ('taskObject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='status_history', to='backend_app.TaskObject')),
            ],
        ),
        migrations.CreateModel(
            name='DataProduct',
            fields=[
                ('taskobject_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='backend_app.TaskObject')),
                ('filename', models.CharField(default='unknown', max_length=200)),
                ('description', models.CharField(default='unknown', max_length=255)),
                ('dataproduct_type', models.CharField(default='raw', max_length=50, verbose_name='type')),
                ('size', models.BigIntegerField(default=0)),
                ('quality', models.CharField(default='unknown', max_length=30)),
                ('parent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='generated_dataproducts', to='backend_app.Observation')),
            ],
            bases=('backend_app.taskobject',),
        ),
    ]
