# Generated by Django 2.2.6 on 2019-10-13 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='observation',
            name='observing_mode',
            field=models.CharField(default='digcam', max_length=50),
        ),
    ]
