# Generated by Django 2.2.6 on 2019-10-13 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend_app', '0002_observation_observing_mode'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dataproduct',
            name='dataproduct_type',
            field=models.CharField(default='raw', max_length=50, verbose_name='Dataproduct Type'),
        ),
    ]
