# Generated by Django 2.2.6 on 2019-10-16 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend_app', '0003_auto_20191013_2028'),
    ]

    operations = [
        migrations.AddField(
            model_name='taskobject',
            name='job',
            field=models.CharField(default='', max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='taskobject',
            name='data_location',
            field=models.CharField(blank=True, default=None, max_length=255, null=True),
        ),
    ]
