# Generated by Django 2.2.6 on 2019-10-26 05:46

import backend_app.models
import backend_app.services.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend_app', '0004_auto_20191016_1406'),
    ]

    operations = [
        migrations.CreateModel(
            name='AstroFile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(storage=backend_app.services.storage.OverwriteStorage(), upload_to=backend_app.models.my_directory_path)),
                ('directory', models.CharField(blank=True, max_length=128)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
