# Generated by Django 2.2.6 on 2019-10-26 06:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend_app', '0005_astrofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='astrofile',
            name='new_filename',
            field=models.CharField(blank=True, max_length=80),
        ),
    ]
