# Generated by Django 2.2.6 on 2019-10-30 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend_app', '0007_observation_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='observation',
            name='url',
            field=models.CharField(default='', max_length=100),
        ),
    ]
