# Generated by Django 2.2.6 on 2019-11-23 09:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backend_app', '0008_observation_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='observation',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='backend_app.TaskObject'),
        ),
        migrations.AlterField(
            model_name='observation',
            name='description',
            field=models.CharField(blank=True, default='', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='observation',
            name='observing_mode',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='observation',
            name='quality',
            field=models.CharField(default='', max_length=30),
        ),
    ]
