# Generated by Django 2.2.6 on 2020-08-08 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend_app', '0010_auto_20200719_0944'),
    ]

    operations = [
        migrations.AddField(
            model_name='observation',
            name='exposure_in_seconds',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='observation',
            name='image_type',
            field=models.CharField(choices=[('solar system', 'solar system'), ('stars wide angle', 'stars wide angle'), ('stars zoomed-in', 'stars zoomed-in'), ('deep sky', 'deep sky'), ('moon', 'moon'), ('spacecraft', 'spacecraft'), ('scenery', 'scenery'), ('technical', 'technical'), ('event', 'event'), ('other', 'other')], default='other', max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='observation',
            name='iso',
            field=models.CharField(choices=[('none', 'none'), ('100', '100'), ('200', '200'), ('400', '400'), ('800', '800'), ('1600', '1600'), ('3200', '3200'), ('6400', '6400')], default='none', max_length=4, null=True),
        ),
        migrations.AddField(
            model_name='observation',
            name='magnitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='observation',
            name='stacked_images',
            field=models.IntegerField(default=0),
        ),
    ]
