# Generated by Django 2.2.6 on 2020-08-08 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend_app', '0011_auto_20200808_1210'),
    ]

    operations = [
        migrations.AddField(
            model_name='observation',
            name='focal_length',
            field=models.IntegerField(default=0),
        ),
    ]
