# Generated by Django 2.2.6 on 2020-08-08 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend_app', '0012_observation_focal_length'),
    ]

    operations = [
        migrations.AlterField(
            model_name='observation',
            name='focal_length',
            field=models.IntegerField(default=200),
        ),
        migrations.AlterField(
            model_name='observation',
            name='stacked_images',
            field=models.IntegerField(default=1),
        ),
    ]
