# Generated by Django 2.2.6 on 2020-08-09 05:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend_app', '0013_auto_20200808_1849'),
    ]

    operations = [
        migrations.AlterField(
            model_name='observation',
            name='magnitude',
            field=models.CharField(blank=True, max_length=5, null=True),
        ),
    ]
