# Generated by Django 2.2.6 on 2020-09-24 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend_app', '0014_auto_20200809_0718'),
    ]

    operations = [
        migrations.AlterField(
            model_name='observation',
            name='url',
            field=models.CharField(blank=True, default='', max_length=100, null=True),
        ),
    ]
