# Generated by Django 2.2.6 on 2020-09-26 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend_app', '0016_collection'),
    ]

    operations = [
        migrations.AddField(
            model_name='collection',
            name='date',
            field=models.DateTimeField(null=True, verbose_name='date'),
        ),
    ]
