# Generated by Django 2.2.6 on 2020-11-11 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend_app', '0017_collection_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='observation',
            name='observing_mode',
        ),
        migrations.AddField(
            model_name='observation',
            name='filter',
            field=models.CharField(choices=[('None', 'None'), ('CLS', 'CLS')], default='CLS', max_length=50),
        ),
        migrations.AddField(
            model_name='observation',
            name='instrument',
            field=models.CharField(choices=[('Powershot G2', 'Powershot G2'), ('Powershot G15', 'Powershot G15'), ('Canon 350D', 'Canon 350D'), ('Canon 2000D', 'Canon 2000D')], default='Canon 2000D', max_length=50),
        ),
        migrations.AlterField(
            model_name='observation',
            name='quality',
            field=models.CharField(default='good', max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='taskobject',
            name='job',
            field=models.CharField(blank=True, default='', max_length=15, null=True),
        ),
    ]
