# Generated by Django 2.2.6 on 2020-11-14 18:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend_app', '0018_auto_20201111_1905'),
    ]

    operations = [
        migrations.CreateModel(
            name='Command',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('command', models.CharField(default='unknown', max_length=50)),
                ('type', models.CharField(default='unknown', max_length=10)),
                ('rights', models.CharField(choices=[('superuser', 'superuser'), ('anonymous', 'anonymous')], default='superuser', max_length=10)),
                ('parameters', models.CharField(default='unknown', max_length=200)),
            ],
        ),
    ]
