# Generated by Django 2.2.6 on 2020-11-15 06:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backend_app', '0020_auto_20201114_1940'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='command',
            name='parameters',
        ),
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_id', models.CharField(default='unknown', max_length=10)),
                ('parameters', models.CharField(default='', max_length=200, null=True)),
                ('status', models.CharField(default='defined', max_length=50, null=True)),
                ('result', models.CharField(default='', max_length=200, null=True)),
                ('command', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='backend_app.Command')),
            ],
        ),
    ]
