# Generated by Django 2.2.6 on 2020-11-15 06:51

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend_app', '0021_auto_20201115_0732'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='job',
            name='job_id',
        ),
        migrations.AddField(
            model_name='job',
            name='creationTime',
            field=models.DateTimeField(blank=True, default=datetime.datetime.utcnow),
        ),
    ]
