# Generated by Django 2.2.13 on 2020-11-17 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend_app', '0022_auto_20201115_0751'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='type',
            field=models.CharField(default='', max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='job',
            name='command',
            field=models.CharField(default='', max_length=200, null=True),
        ),
    ]
