# Generated by Django 2.2.13 on 2020-11-17 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend_app', '0024_auto_20201117_1928'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='parameters',
            field=models.CharField(blank=True, default='', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='job',
            name='result',
            field=models.CharField(blank=True, default='', max_length=200, null=True),
        ),
    ]
