# Generated by Django 2.2.13 on 2020-11-18 07:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend_app', '0025_auto_20201117_1932'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Command',
        ),
        migrations.RemoveField(
            model_name='job',
            name='type',
        ),
    ]
