# Generated by Django 2.2.13 on 2020-11-28 09:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend_app', '0027_auto_20201127_2035'),
    ]

    operations = [
        migrations.AddField(
            model_name='observation',
            name='ra_dec_fov',
            field=models.CharField(blank=True, max_length=8, null=True),
        ),
    ]
