# Generated by Django 2.2.13 on 2020-11-28 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend_app', '0028_observation_ra_dec_fov'),
    ]

    operations = [
        migrations.AlterField(
            model_name='observation',
            name='ra_dec_fov',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
