# Generated by Django 2.2.13 on 2020-11-29 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend_app', '0029_auto_20201128_1028'),
    ]

    operations = [
        migrations.AddField(
            model_name='taskobject',
            name='astrometry_url',
            field=models.CharField(blank=True, default='', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='observation',
            name='dec_max',
            field=models.FloatField(blank=True, null=True, verbose_name='dec_max'),
        ),
        migrations.AlterField(
            model_name='observation',
            name='dec_min',
            field=models.FloatField(blank=True, null=True, verbose_name='dec_min'),
        ),
        migrations.AlterField(
            model_name='observation',
            name='ra_max',
            field=models.FloatField(blank=True, null=True, verbose_name='ra_max'),
        ),
        migrations.AlterField(
            model_name='observation',
            name='ra_min',
            field=models.FloatField(blank=True, null=True, verbose_name='ra_min'),
        ),
    ]
