# Generated by Django 3.1.4 on 2020-12-19 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend_app', '0032_observation_used_in_hips'),
    ]

    operations = [
        migrations.CreateModel(
            name='ObservationBox',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('backend_app.observation',),
        ),
        migrations.AddField(
            model_name='observation',
            name='box',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
