# Generated by Django 3.1.8 on 2021-04-28 05:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend_app', '0033_auto_20201219_1351'),
    ]

    operations = [
        migrations.AlterField(
            model_name='observation',
            name='used_in_hips',
            field=models.BooleanField(default=True),
        ),
    ]
