# Generated by Django 3.1.8 on 2021-04-28 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend_app', '0034_auto_20210428_0730'),
    ]

    operations = [
        migrations.AddField(
            model_name='observation',
            name='extra',
            field=models.TextField(blank=True, null=True),
        ),
    ]
