# Generated by Django 3.1.8 on 2021-04-28 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend_app', '0035_observation_extra'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='extra',
            field=models.TextField(blank=True, null=True),
        ),
    ]
