# Generated by Django 3.1.8 on 2021-04-29 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend_app', '0036_job_extra'),
    ]

    operations = [
        migrations.AddField(
            model_name='observation',
            name='transients',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
