# Generated by Django 3.1.8 on 2021-04-29 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend_app', '0037_observation_transients'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='observation',
            name='transients',
        ),
        migrations.AddField(
            model_name='observation',
            name='transient',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
