# Generated by Django 3.1.8 on 2021-05-02 14:12

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backend_app', '0038_auto_20210429_1928'),
    ]

    operations = [
        migrations.CreateModel(
            name='Observation2',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='unknown', max_length=100)),
                ('task_type', models.CharField(choices=[('master', 'master'), ('observation', 'observation')], default='dataproduct', max_length=20)),
                ('taskID', models.CharField(blank=True, db_index=True, max_length=30, null=True, verbose_name='taskID')),
                ('creationTime', models.DateTimeField(blank=True, default=datetime.datetime.utcnow)),
                ('new_status', models.CharField(default='defined', max_length=50, null=True)),
                ('data_location', models.CharField(blank=True, default=None, max_length=255, null=True)),
                ('my_status', models.CharField(db_index=True, default='defined', max_length=50)),
                ('astrometry_url', models.CharField(blank=True, default='http://nova.astrometry.net', max_length=50, null=True)),
                ('job', models.CharField(blank=True, default='', max_length=15, null=True)),
                ('date', models.DateTimeField(null=True, verbose_name='date')),
                ('instrument', models.CharField(choices=[('Powershot G2', 'Powershot G2'), ('Powershot G15', 'Powershot G15'), ('Canon 350D', 'Canon 350D'), ('Canon 2000D', 'Canon 2000D')], default='Canon 2000D', max_length=50)),
                ('filter', models.CharField(choices=[('None', 'None'), ('CLS', 'CLS')], default='CLS', max_length=50)),
                ('description', models.CharField(blank=True, default='', max_length=255, null=True)),
                ('url', models.CharField(blank=True, default='', max_length=100, null=True)),
                ('field_name', models.CharField(max_length=255, null=True)),
                ('field_ra', models.FloatField(null=True, verbose_name='field_ra')),
                ('field_dec', models.FloatField(null=True, verbose_name='field_dec')),
                ('field_fov', models.FloatField(null=True, verbose_name='field_fov')),
                ('ra_min', models.FloatField(blank=True, null=True, verbose_name='ra_min')),
                ('ra_max', models.FloatField(blank=True, null=True, verbose_name='ra_max')),
                ('dec_min', models.FloatField(blank=True, null=True, verbose_name='dec_min')),
                ('dec_max', models.FloatField(blank=True, null=True, verbose_name='dec_max')),
                ('ra_dec_fov', models.CharField(blank=True, max_length=30, null=True)),
                ('box', models.CharField(blank=True, max_length=255, null=True)),
                ('quality', models.CharField(default='good', max_length=30, null=True)),
                ('iso', models.CharField(choices=[('none', 'none'), ('100', '100'), ('200', '200'), ('400', '400'), ('800', '800'), ('1600', '1600'), ('3200', '3200'), ('6400', '6400')], default='none', max_length=4, null=True)),
                ('focal_length', models.IntegerField(default=200)),
                ('exposure_in_seconds', models.IntegerField(default=0)),
                ('stacked_images', models.IntegerField(default=1)),
                ('magnitude', models.CharField(blank=True, max_length=5, null=True)),
                ('image_type', models.CharField(choices=[('solar system', 'solar system'), ('stars wide angle', 'stars wide angle'), ('stars zoomed-in', 'stars zoomed-in'), ('deep sky', 'deep sky'), ('moon', 'moon'), ('spacecraft', 'spacecraft'), ('scenery', 'scenery'), ('technical', 'technical'), ('event', 'event'), ('other', 'other')], default='other', max_length=20, null=True)),
                ('used_in_hips', models.BooleanField(default=True)),
                ('extra', models.TextField(blank=True, null=True)),
                ('transient', models.CharField(blank=True, max_length=30, null=True)),
                ('size', models.BigIntegerField(blank=True, null=True)),
                ('dps', models.TextField(blank=True, null=True)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='children', to='backend_app.observation2')),
            ],
        ),
    ]
