# Generated by Django 3.1.8 on 2021-05-04 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend_app', '0040_auto_20210502_1653'),
    ]

    operations = [
        migrations.CreateModel(
            name='Collection2',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(null=True, verbose_name='date')),
                ('name', models.CharField(default='unknown', max_length=100)),
                ('collection_type', models.CharField(choices=[('solar system', 'solar system'), ('stars wide angle', 'stars wide angle'), ('stars zoomed-in', 'stars zoomed-in'), ('deep sky', 'deep sky'), ('moon', 'moon'), ('spacecraft', 'spacecraft'), ('scenery', 'scenery'), ('technical', 'technical'), ('event', 'event'), ('other', 'other')], default='other', max_length=20, null=True)),
                ('description', models.CharField(blank=True, default='', max_length=255, null=True)),
                ('observations', models.ManyToManyField(to='backend_app.Observation2')),
            ],
        ),
    ]
