# Generated by Django 3.1.8 on 2021-05-08 09:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend_app', '0044_auto_20210508_0718'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='collection',
            name='observations',
        ),
        migrations.RemoveField(
            model_name='dataproduct',
            name='parent',
        ),
        migrations.RemoveField(
            model_name='dataproduct',
            name='taskobject_ptr',
        ),
        migrations.RemoveField(
            model_name='observation',
            name='parent',
        ),
        migrations.RemoveField(
            model_name='observation',
            name='taskobject_ptr',
        ),
        migrations.RemoveField(
            model_name='status',
            name='taskObject',
        ),
        migrations.DeleteModel(
            name='ObservationBox',
        ),
        migrations.DeleteModel(
            name='Collection',
        ),
        migrations.DeleteModel(
            name='DataProduct',
        ),
        migrations.DeleteModel(
            name='Observation',
        ),
        migrations.DeleteModel(
            name='Status',
        ),
        migrations.DeleteModel(
            name='TaskObject',
        ),
    ]
