# Generated by Django 3.1.13 on 2021-11-14 07:15

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backend_app', '0047_auto_20210718_1222'),
    ]

    operations = [
        migrations.AlterField(
            model_name='observation2',
            name='task_type',
            field=models.CharField(choices=[('master', 'master'), ('observation', 'observation')], default='observation', max_length=20),
        ),
        migrations.CreateModel(
            name='Cutout',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creationTime', models.DateTimeField(blank=True, default=datetime.datetime.utcnow)),
                ('directory', models.CharField(max_length=80, null=True)),
                ('filename', models.CharField(blank=True, max_length=80)),
                ('field_name', models.CharField(max_length=100, null=True)),
                ('field_ra', models.FloatField(null=True, verbose_name='field_ra')),
                ('field_dec', models.FloatField(null=True, verbose_name='field_dec')),
                ('field_fov', models.FloatField(null=True, verbose_name='field_fov')),
                ('cutout_size', models.IntegerField(default=500)),
                ('order', models.IntegerField(default=0)),
                ('quality', models.CharField(default='good', max_length=30, null=True)),
                ('observation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cutouts', to='backend_app.observation2')),
            ],
        ),
    ]
