# Generated by Django 3.1.13 on 2021-11-14 08:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend_app', '0049_auto_20211114_0823'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cutout',
            name='quality',
            field=models.CharField(default='unknown', max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='cutout',
            name='status',
            field=models.CharField(default='unknown', max_length=15, null=True),
        ),
    ]
