# Generated by Django 3.1.13 on 2021-11-14 08:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend_app', '0050_auto_20211114_0908'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cutout',
            name='id',
        ),
        migrations.AlterField(
            model_name='cutout',
            name='filename',
            field=models.CharField(db_index=True, max_length=80, primary_key=True, serialize=False),
        ),
    ]
