# Generated by Django 3.1.13 on 2021-11-14 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend_app', '0051_auto_20211114_0944'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cutout',
            old_name='quality',
            new_name='cutout_quality',
        ),
        migrations.AddField(
            model_name='cutout',
            name='delete',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='cutout',
            name='observation_quality',
            field=models.CharField(default='unknown', max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='cutout',
            name='visible',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='cutout',
            name='filename',
            field=models.CharField(blank=True, db_index=True, max_length=80, primary_key=True, serialize=False),
        ),
    ]
