# Generated by Django 3.1.13 on 2021-11-14 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend_app', '0052_auto_20211114_1057'),
    ]

    operations = [
        migrations.CreateModel(
            name='CutoutDirectory',
            fields=[
                ('directory', models.CharField(db_index=True, max_length=80, primary_key=True, serialize=False)),
                ('field_name', models.CharField(max_length=100, null=True)),
                ('field_ra', models.FloatField(null=True, verbose_name='field_ra')),
                ('field_dec', models.FloatField(null=True, verbose_name='field_dec')),
                ('field_fov', models.FloatField(null=True, verbose_name='field_fov')),
                ('cutout_size', models.IntegerField(default=500)),
                ('visible', models.BooleanField(default=True)),
                ('status', models.CharField(default='empty', max_length=15, null=True)),
                ('number_of_images', models.IntegerField(default=0)),
                ('thumbnail', models.CharField(blank=True, max_length=80, null=True)),
            ],
        ),
    ]
