# Generated by Django 3.1.13 on 2021-11-14 13:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backend_app', '0053_cutoutdirectory'),
    ]

    operations = [
        migrations.AddField(
            model_name='cutout',
            name='cutout_directory',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cutouts', to='backend_app.cutoutdirectory'),
        ),
    ]
