# Generated by Django 3.1.13 on 2021-11-14 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend_app', '0054_cutout_cutout_directory'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cutout',
            name='observation',
        ),
        migrations.AddField(
            model_name='cutout',
            name='observation_taskID',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='taskID'),
        ),
    ]
