# Generated by Django 3.1.13 on 2021-12-03 07:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend_app', '0057_auto_20211120_2008'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='celery_id',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='job',
            name='queue',
            field=models.CharField(default='astrobase_services', max_length=30, null=True),
        ),
    ]
