version: "3.7"
services:
  web:
    build: .
    container_name: astrobase_web_dev
    ports:
      - "8018:8018"
    expose:
      - "8018"

    restart: always

  nginx:
    build:
       context: ./docker/nginx
       dockerfile: Dockerfile
    container_name: astrobase_nginx_dev
    ports:
      - "89:8019"
    volumes:
      - ./docker/nginx:/etc/nginx/conf.d
      - /home/vagrant/shared/astrobase/static:/static
    depends_on:
      - web
    restart: always


