version: "3.7"
services:
  web:
    build:
        context: .
        dockerfile: Dockerfile_compose
    container_name: astrobase_web_compose
    ports:
      - "8008:8008"
    expose:
      - "8008"
    restart: always
    volumes:
      # this is where the sqlite database lives
      - /home/pi/shared:/shared
  nginx:
    build:
       context: ./docker/nginx
       dockerfile: Dockerfile
    container_name: astrobase_nginx_compose
    ports:
      - "89:8009"
    volumes:
      - ./docker/nginx:/etc/nginx/conf.d
      - /home/pi/shared/astrobase/static:/static
    depends_on:
      - web
    restart: always

