FROM python:3.6.7-slim
ENV PYTHONUNBUFFERED 1
RUN apt-get update && apt-get install --no-install-recommends -y bash nano mc

RUN mkdir /src
WORKDIR /src
COPY . /src/
RUN pip install -r requirements/prod.txt
# RUN exec python manage.py collectstatic --settings=astrobase.settings.docker --no-input
CMD exec gunicorn astrobase.wsgi_docker_rpi:application --bind 0.0.0.0:8008 --workers 3
