name: deploy-docker-woodland
on:
  workflow_dispatch:
jobs:
  deploy-docker-woodland:
    runs-on: ubuntu-latest
    steps:
      - name: execute build & deploy procedure on woodlnd
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.MY_HOST }}
          port: 22
          username: ${{ secrets.MY_USERNAME }}
          password: ${{ secrets.MY_PASSWORD }}
          #key: ${{ secrets.MY_PRIVATE_KEY }}
          script: |
             cd ~/my_docker/MyAstroBase
             git pull
             cd astrobase
             docker build -t my_astrobase:latest .
             cd $HOME/shared
             docker stop my_astrobase
             docker rm -f my_astrobase
             docker compose -p astronest -f ~/shared/docker-compose-astro.yml up -d