name: build-deploy-astrobase
on: [push]
jobs:
  build-deploy-astrobase:
    runs-on: ubuntu-latest
    steps:
      - name: execute build & deploy procedure on mintbox
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.MY_HOST }}
          username: ${{ secrets.MY_USERNAME }}
          password: ${{ secrets.MY_PASSWORD }}
          script: |
             cd ~/my_docker/MyAstroBase
             git pull
             cd astrobase
             sudo docker build -t my_astrobase:latest .
            cd $HOME/shared
            sudo docker-compose -p dockernest up -d