name: build-deploy-astrobase
on: [push]
jobs:
  build-deploy-astrobase:
    runs-on: ubuntu-latest
    steps:
      - name: execute build & deploy procedure on mintbox
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.MY_HOST }}
          username: ${{ secrets.MY_USERNAME }}
          password: ${{ secrets.MY_PASSWORD }}
          #key: ${{ secrets.MY_PRIVATE_KEY }}
          script: |
             cd ~/my_docker/MyAstroBase
             git pull
             cd astrobase
             docker build -t my_astrobase:latest .
             cd $HOME/shared
             docker stop my_astrobase
             docker rm -f my_astrobase
             docker-compose -p astronest -f ~/shared/docker-compose-astro.yml up -d